### ISSUE TITLE
Access  is denied??

### ISSUE THREAD

**Issue by Danyal-noorani** [UnamSanctam/UnamBinder#57]
im trying to bind two files togeather but everytime it keeps giving me a Access is denied error with Native C

while trying it with Managed i get :
System.Runtime.InteropServices.ExternalException (0x80004005): Cannot execute a program. The command being executed was "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /noconfig /fullpaths @"C:\Users\xxxx\AppData\Local\Temp\lstq1glx\lstq1glx.cmdline". ---> System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.CodeDom.Compiler.Executor.ExecWaitWithCaptureUnimpersonated(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCapture(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at Microsoft.CSharp.CSharpCodeGenerator.Compile(CompilerParameters options, String compilerDirectory, String compilerExe, String arguments, String& outputFile, Int32& nativeReturnValue, String trueArgs)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at UnamBinder.Builder.ManagedCompiler(String savePath)
   at UnamBinder.Builder.btnBuild_Click(Object sender, EventArgs e)

Ive tried lauching the binder with admin rights but no use 
happenes with every file

any idea how to fix this

**Comment by UnamSanctam** [comment]
That's almost always because it doesn't have permissions to write the program where you're saving it, where are you trying to save it?

**Comment by Danyal-noorani** [comment]
Oh okay i was saving it in the same directory as the binder.exe
changed it and works thanks alot
